

<h1><center>Pytorch Introduction</center></h1>

PyTorch is an open-source machine learning framework developed by Facebook's AI research team. It is a popular choice for building deep learning models and is known for its flexibility, ease of use, and speed. PyTorch allows developers to create and train neural networks, perform numerical computations, and implement complex algorithms with ease. It provides various tools and libraries that make it easy to work with complex data and models, such as torch.autograd for automatic differentiation, torch.nn for building neural networks, and torch.optim for optimization algorithms. PyTorch is widely used in both research and industry applications and is considered one of the top deep learning frameworks available.

## Basic commands and Libraries

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cpu


## Introduction to Tensors

Fundamental building blocks of the neural network
1. `Scalar`
2. `Vector`
3. `Tensor`
4. `Matrix`

## Scalar and Vectors - 1 and 2 Dimensions

In [3]:
# Scalar - one dimension

scalar = torch.tensor(7)
scalar

tensor(7)

In [64]:
scalar.ndim

0

In [5]:
scalar.shape

torch.Size([])

In [6]:
# Vector - two dimensions

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

## Matrixes and Tensors - Multiple Dimensions

In [9]:
# Matrix 

MATRIX = torch.tensor([[7,8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# Tensor

TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [65]:
# Testing tensors
TENSOR_test = torch.tensor([[[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]]])
TENSOR_test

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])

In [17]:
TENSOR_test.shape, TENSOR_test.ndim

(torch.Size([1, 1, 3, 3]), 4)

### Random tensors

Random tensors are important, because the way neural networks learns is by starting with a tensors full 
of random numbers and then ajust those random numbers to better represent the data.

look at numbers -> update -> repeat


In [18]:
# Creating random tensors

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3369, 0.5594, 0.7457, 0.5202],
        [0.6911, 0.9547, 0.5489, 0.1945],
        [0.0610, 0.1490, 0.6235, 0.3518]])

In [19]:
# Creating random tensors with similar shape to an image

random_image_size_tensor = torch.rand(224, 224, 3) #heiht, width (both in pixels), color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [20]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [66]:
print(zeros.dtype)
print(ones.dtype)

torch.float32
torch.float32


### Creating a range of tensors

In [23]:
one_ten = torch.arange(0, 10)
one_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#Creating tensors like
ten_zeros = torch.zeros_like(one_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensors datatypes, shape and device


In [74]:
# Datatype

float_32_dtype = torch.tensor([3.0, 6.0, 9.0],
                             dtype=None,
                             device=None,
                             requires_grad=False)
float_32_dtype

tensor([3., 6., 9.])

In [26]:
float_32_dtype.dtype

torch.float32

In [27]:
# Changing the datatype
float_16_dtype = float_32_dtype.type(torch.float16)
float_16_dtype

tensor([3., 6., 9.], dtype=torch.float16)

### Creating Tensors

In [28]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3233, 0.5695, 0.6820, 0.9178],
        [0.1521, 0.9426, 0.2499, 0.7729],
        [0.7139, 0.5896, 0.5008, 0.2854]])

In [29]:
# Details about the tensor

print(random_tensor)
print(random_tensor.dtype)
print(random_tensor.shape)
print(random_tensor.device)

tensor([[0.3233, 0.5695, 0.6820, 0.9178],
        [0.1521, 0.9426, 0.2499, 0.7729],
        [0.7139, 0.5896, 0.5008, 0.2854]])
torch.float32
torch.Size([3, 4])
cpu


## Tensors Operations

In [30]:
tensor1 = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
tensor1 + 10

tensor([[11, 12, 13],
        [14, 15, 16]])

In [31]:
tensor1 - 10

tensor([[-9, -8, -7],
        [-6, -5, -4]])

In [32]:
tensor1 * 10
# Or
torch.mul(tensor1, 10)

tensor([[10, 20, 30],
        [40, 50, 60]])

In [33]:
tensor1 / 10

tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000]])

### Matrix Multiplication

In [34]:
torch.matmul(tensor1, tensor1.T)
# Or
torch.mm(tensor1, tensor1.T)
# Or
tensor_final = tensor1 @ tensor1.T
tensor_final

tensor([[14, 32],
        [32, 77]])

In [35]:
tensor_final.shape

torch.Size([2, 2])

### Tensor Aggregation
sum, mean, max, min

In [36]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [37]:
# Sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [38]:
# Min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [39]:
# Max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [40]:
# Mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [41]:
# Finding the position of the max value
x.argmax()
# The max value is in the position 9

tensor(9)

### Reshaping, view and stack

In [69]:
x = torch.arange(1., 10.)
x, x.shape, x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), 1)

In [67]:
# Adding one dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]), 2)

In [44]:
# Changing the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [45]:
# Stacking
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [46]:
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [47]:
#Squeeze reduces one dimention
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [48]:
x_squeezed.shape

torch.Size([9])

In [49]:
#Unsqueeze adds one dimention
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [50]:
x_unsqueezed.shape

torch.Size([1, 9])

In [51]:
# Permute rearanges the tensor dimensional order
x_original = torch.rand(224, 224, 3)
print(x_original.shape)

x_permuted = x_original.permute(2, 0, 1)
print(x_permuted.shape) 

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


### Indexing - Selecting data from tensors

In [70]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape, x.ndim

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]),
 3)

In [53]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [54]:
x[0][0]

tensor([1, 2, 3])

In [55]:
x[0][0][0]

tensor(1)

### PyTorch Tensors vs NumPy Datatypes

In [72]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, array.dtype, tensor, tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 torch.float64)

As shown above, the dtype of array on numpy and the dtype of pytorch are different

### Manipulating RNG in PyTorch

Reproduciability - Helpful when trying to reproduce the same model elsewhere

In [58]:
# Creating a Manual Seed

RANDOM_SEED = 10

torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])
tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Accessing the GPU for faster computation

In [59]:
!nvidia-smi

Fri Jan  6 19:13:20 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 516.94       Driver Version: 516.94       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:07:00.0  On |                  N/A |
| 36%   39C    P0    30W / 135W |    987MiB /  6144MiB |      5%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [60]:
torch.cuda.is_available()

False

In [61]:
torch.backends.cudnn.enabled

True

## Device - Using the models on the GPU

In [62]:
tensor = torch.tensor([1, 2, 3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [73]:
'''
# The device is set to "cuda", if available

device = "cuda"
tensor_on_gpu = tensor.to(device)
'''

'\nThe device is set to "cuda", if available\n\ndevice = "cuda"\ntensor_on_gpu = tensor.to(device)\n'

## Most commons errors with tensors

1. tensors not in the right datatype - `tensor.dtype`
2. tensors not in the right shape - `tensor.shape`
3. tensors not in the right device - `tensor.device`